attempt 3

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -6,7 +6,7 @@ concurrency:
 
 on:
   push:
-    branches: [ "main" ]
+    tags: [ "*" ]
   workflow_dispatch:
 
 jobs:
@@ -14,26 +14,40 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Get changed files
-        id: changed-files
-        uses: tj-actions/changed-files@v39
-
       - uses: actions/checkout@v3
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
+
+      # Run this step first so we can fail fast in case an invalid package name is provided
+      - name: Get latest package version
+        id: latest-package-version
+        uses: ./.github/actions/latest-package-version
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          package-name: uds-package/software-factory-demo
+
+      - name: Compare latest version with current
+        run: |
+          NEW_VERSION="$(cat uds-bundle.yaml | grep version | cut -d ':' -f2 | tr -d " ")"
+          CURRENT_VERSION="${{ steps.latest-package-version.outputs.latest-package-version}}"
+          CURRENT_VERSION=${CURRENT_VERSION//v/}
+          CURRENT_VERSION=${CURRENT_VERSION//-amd64/}
+          echo "Current version: ${CURRENT_VERSION}"
+          NEWER_VERSION=$(echo -e "${CURRENT_VERSION}\n${NEW_VERSION}" | sort -V | tail -n1)
+          # Fail if newer version is not upstream version
+          if [[ "${NEWER_VERSION}" == "${CURRENT_VERSION}" ]]; then
+            echo "Bundle version was not updated"
+            exit 1
+          else
+            echo "Bundle version was updated"
+            exit 0
+          fi
 
       - name: Init zarf cache
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         uses: actions/cache@v3
         with:
           path: "~/.zarf-cache"
           key: zarf-cache
 
       - name: Free GH runner build space
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -44,7 +58,6 @@ jobs:
           df -h
 
       - name: Install zarf
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         uses: supplypike/setup-bin@v3
         with:
           # renovate: zarf-uri datasource=github-tags depName=defenseunicorns/zarf
@@ -54,7 +67,6 @@ jobs:
           version: 'v0.29.1'
 
       - name: Install uds-cli
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         uses: supplypike/setup-bin@v3
         with:
           # renovate: uds-cli-uri datasource=github-tags depName=defenseunicorns/uds-cli
@@ -64,7 +76,6 @@ jobs:
           version: 'v0.0.4-alpha'
 
       - name: Login to GHCR
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
@@ -72,7 +83,6 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Login to registry1
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         uses: docker/login-action@v2
         with:
           registry: registry1.dso.mil
@@ -80,7 +90,6 @@ jobs:
           password: ${{ secrets.REGISTRY1_PASSWORD }}
 
       - name: Build Software Factory Dependencies Packages
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         run: |
           mkdir -p build
           zarf package create packages/idam-dns       --confirm --no-progress --output-directory build
@@ -90,9 +99,7 @@ jobs:
           zarf package create packages/namespaces     --confirm --no-progress --output-directory build
 
       - name: Build software factory bundle
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         run: uds bundle create --confirm --no-progress
 
       - name: Publish software factory bundle
-        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
         run: uds bundle publish uds-bundle-software-factory-demo-amd64-*.tar.zst oci://ghcr.io/defenseunicorns/uds-package --no-progress
